[package]
name = "transpaer-wikidata"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
bzip2 = { workspace = true }
flate2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
